name       : mypaint
version    : 2.0.1
release    : 19
source     :
    - https://github.com/mypaint/mypaint/releases/download/v2.0.1/mypaint-2.0.1.tar.xz : f3e437d7cdd5fd28ef6532e8ab6b4b05d842bcdd644f16a0162dad3d8e57bb16
homepage   : http://mypaint.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : MyPaint is a simple drawing and painting program that works well with Wacom-style graphics tablets
description: |
    MyPaint is a simple drawing and painting program that works well with Wacom-style graphics tablets.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libmypaint)
    - pkgconfig(mypaint-brushes-2.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - numpy
    - python-protobuf
    - swig
rundeps    :
    - numpy
    - mypaint-brushes
    - python-gobject
    - python-protobuf
build      : |
    %python3_setup
install    : |
    %python3_install
