name       : xorg-xwayland
version    : 22.1.8
release    : 15
source     :
    - https://xorg.freedesktop.org/archive/individual/xserver/xwayland-22.1.8.tar.xz : d11eeee73290b88ea8da42a7d9350dedfaba856ce4ae44e58c045ad9ecaa2f73
license    : MIT
component  : xorg.server
summary    : X server intended for Xorg only clients to run under Wayland for backwards compatability.
description: |
    X server intended for Xorg only clients to run under Wayland for backwards compatability.
patterns   : /*
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(epoxy)
    - pkgconfig(fontutil)
    - pkgconfig(gdm)
    - pkgconfig(libdrm)
    - pkgconfig(libtirpc)
    - pkgconfig(libxcvt)
    - pkgconfig(inputproto)
    - pkgconfig(nettle)
    - pkgconfig(pixman-1)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-eglstream-protocols)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xfont2)
    - pkgconfig(xkbcomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xshmfence)
    - pkgconfig(xtrans)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Provided by xorg-server
    rm -fr $installdir/usr/lib64/xorg/
    rm $installdir/usr/share/man/man1/Xserver.1
