name       : python-constantly
version    : 15.1.0
release    : 6
source     :
    - https://github.com/twisted/constantly/archive/15.1.0.tar.gz : be63c40ef853ee785045a1d20327d8153db9291f9aaff552796bed5272f9dd60
homepage   : https://github.com/twisted/constantly
license    : MIT
component  : programming.python
summary    : Symbolic Constants in Python
description: |
    A library that provides symbolic constant support. It includes collections and constants with text, numeric, and bit flag values. Originally twisted.python.constants from the Twisted project.
builddeps  :
    - pytest-runner
    - python-incremental
    - python-twisted     # check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test setup.py ptr
