name       : bottom
version    : 0.7.1
release    : 14
source     :
    - https://github.com/ClementTsang/bottom/archive/refs/tags/0.7.1.tar.gz : 9d92688cceabac54ac47b7edcea3f858931b8f69661afb0d11dddc0bad5d3584
    - https://github.com/ClementTsang/bottom/releases/download/0.7.1/completion.tar.gz : 7c166e22c18d61ff2b3a624c86a698238326bc905e965c01114fce73457c5bf7
    - https://github.com/ClementTsang/bottom/releases/download/0.7.1/manpage.tar.gz : 534985ee5c83f115d1c446fda7527b611eb892d230fd371ae041db639b10d906
license    : MIT
component  : system.utils
summary    : Yet another cross-platform graphical process/system monitor.
description: |
    A cross-platform graphical process/system monitor with a customizable interface and a multitude of features. Supports Linux, macOS, and Windows. Inspired by both gtop and gotop.
networking : yes
builddeps  :
    - cargo
setup      : |
    cp $sources/completion.tar.gz .
    cp $sources/manpage.tar.gz .

    tar xf completion.tar.gz
    tar xf manpage.tar.gz
build      : |
    cargo build --release --bin btm
install    : |
    install -Dm00755 target/release/btm $installdir/usr/bin/btm

    # Completions
    install -Dm00644 btm.bash $installdir/usr/share/bash-completion/completions/btm
    install -Dm00644 _btm $installdir/usr/share/zsh/site-functions/_btm
    install -Dm00644 btm.fish $installdir/usr/share/fish/vendor_completions.d/btm.fish

    # Manpages
    install -Dm00644 btm.1.gz $installdir/usr/share/man/man1/btm.1.gz
