name       : freeciv
version    : 3.0.6
release    : 32
source     :
    - https://github.com/freeciv/freeciv/archive/R3_0_6.tar.gz : fe86a8daf75773b55173824689c91ad7b392e1dd8753572cd718f3503d98bce7
license    : GPL-2.0-or-later
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : no
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(bzip2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
setup      : |
    %autogen
    %configure --disable-static \
        --enable-client=gtk3 \
        --enable-fcdb=sqlite3 \
        --enable-fcmp=gtk3 \
        --enable-ipv6=yes \
        --enable-sdl-mixer=sdl2 \
        --enable-shared \
        --with-readline
build      : |
    %make
install    : |
    %make_install
