name       : python-tenacity
version    : 8.0.1
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/t/tenacity/tenacity-8.0.1.tar.gz : 43242a20e3e73291a28bcbcacfd6e000b02d3857a9a9fff56b297a27afdc932f
homepage   : http://tenacity.readthedocs.io
license    : Apache-2.0
component  : programming.python
summary    : Retrying library for Python
description: |
    Tenacity is a general-purpose retrying library, written in Python, to simplify the task of adding retry behavior to just about anything.
builddeps  :
    - python-pytest
    - python-setuptools-scm
    - python-tornado
    - python-typeguard
rundeps    :
    - python-tornado
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
