name       : anki
version    : 2.1.56
release    : 32
source     :
    - git|https://github.com/ankitects/anki.git : 2.1.56
license    : AGPL-3.0-or-later
component  : office.notes
homepage   : https://apps.ankiweb.net/index.html
networking : yes
summary    : Spaced repetition flashcard program.
description: |
    Anki is a spaced repetition flashcard program. "Anki" is the Japanese word for "memorization". The SM2 algorithm, created for SuperMemo in the late 1980s, forms the basis of the spaced repetition methods employed in the program.
builddeps  :
    - pkgconfig(portaudiocpp)
    - pkgconfig(python3)
    - PyAudio
    - cargo
    - flask-cors
    - mathjax
    - ninja
    - pylint
    - python-beautifulsoup4
    - python-black
    - python-decorator
    - python-distro
    - python-jsonschema
    - python-markdown
    - python-maturin
    - python-mock
    - python-mypy
    - python-orjson
    - python-protobuf
    - python-pytest
    - python-qtpy
    - python-requests
    - python-send2trash
    - python-stringcase
    - python-waitress
    - python-wheel
    - yarn
rundeps    :
    - flask-cors
    - gtk2-engine-murrine
    - mpv
    - PyAudio
    - python-decorator
    - python-distro
    - python-beautifulsoup4
    - python-jsonschema
    - python-markdown
    - python-orjson
    - python-protobuf
    - python-qtpy
    - python-qtwebengine
    - python-send2trash
    - python-stringcase
    - python-waitress
ccache     : no
build      : |
    PYTHON_BINARY=/usr/bin/python3 ./tools/build
install    : |
    python3 -m pip install --isolated --root=$installdir --ignore-installed --no-deps $workdir/out/*.whl
    install -dm00644 $installdir/usr/share/applications
    install -Dm00644 $workdir/qt/bundle/lin/anki.desktop $installdir/usr/share/applications/anki.desktop
