name       : mkvtoolnix
version    : 74.0.0
release    : 80
source     :
    - https://mkvtoolnix.download/sources/mkvtoolnix-74.0.0.tar.xz : b7dc8be6cb9170030de06b983f256ff3cb21efa3209f0efe8e079656fa3d5643
homepage   : https://gitlab.com/mbunkus/mkvtoolnix
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : MKV Toolkit for Linux
description: |
    With these tools one can get information about (mkvinfo) Matroska files, extract tracks/data from (mkvextract) Matroska files and create (mkvmerge) Matroska files from other media files. Matroska is a new multimedia file format aiming to become THE new container format for the future.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(dvdread)
    - pkgconfig(flac)
    - pkgconfig(fmt)
    - pkgconfig(libcmark)
    - pkgconfig(libcurl)
    - pkgconfig(libebml)
    - pkgconfig(libmatroska)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(vorbis)
    - docbook-xml
    - gtest-devel
    - libboost-devel
    - ruby
setup      : |
    %autogen --disable-static --disable-update-check
build      : |
    rake %JOBS% --libdir %libdir%
install    : |
    rake install DESTDIR=$installdir
check      : |
    rake tests:run_unit
