name       : adw-gtk3-theme
version    : '4.4'
release    : 4
source     :
    - https://github.com/lassekongo83/adw-gtk3/archive/refs/tags/v4.4.tar.gz : 4fa2ebd526726f6ab5bd7a1e6fa4c5c0cbb71d504008bc08cf08c9a68f1a1a8a
license    : LGPL-2.1-only
homepage   : https://github.com/lassekongo83/adw-gtk3
component  : desktop.theme
summary    : An unofficial GTK3 port of libadwaita
description: |
    An unofficial GTK3 port of libadwaita
builddeps  :
    - sassc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
