name       : openttd
version    : '13.0'
release    : 36
source     :
    - https://cdn.openttd.org/openttd-releases/13.0/openttd-13.0-source.tar.xz : 339df8e0e0827087c83afe78f8efc6a73b0a3d8a950a0b53137ce6e8aad7ab67
license    : GPL-2.0-or-later
component  : games.strategy
summary    : OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
description: |
    OpenTTD is an open source simulation game based upon Transport Tycoon Deluxe
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(icu-i18n)
    - pkgconfig(liblzma)
    - pkgconfig(lzo2)
    - pkgconfig(sdl2)
setup      : |
    %cmake_ninja \
        -DCMAKE_INSTALL_BINDIR=bin \
        -DCMAKE_INSTALL_DATADIR=share/openttd
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/
