name       : libxi
version    : 1.7.9
release    : 16
source     :
    - https://www.x.org/releases/individual/lib/libXi-1.7.9.tar.gz : 463cc5370191404bc0f8a450fdbf6d9159efbbf274e5e0f427a60191fed9cf4b
license    : MIT
component  : xorg.library
summary    : X Input Extension Library
description: |
    libXi provides an X Window System client interface to the XINPUT extension to the X protocol. The Input extension allows setup and configuration of multiple input devices, and will soon allow hotplugging of input devices; to be added and removed on the fly.
optimize   : speed
emul32     : yes
builddeps  :
    - pkgconfig32(xext)
    - pkgconfig32(x11)
    - pkgconfig32(xfixes)
    - pkgconfig(inputproto)
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
