name       : libcairo
version    : 1.17.8
release    : 51
source     :
    - https://cairographics.org/snapshots/cairo-1.17.8.tar.xz : 5b10c8892d1b58d70d3f0ba5b47863a061262fa56b9dc7944161f8c8b783bc64
license    : LGPL-2.1-or-later
component  : desktop.library
homepage   : https://cairographics.org/
summary    : cairo (2D graphics library)
description: |
    Cairo is a 2D graphics library with support for multiple output devices such as X, Quartz, Win32, image buffers, PS, PDF, and SVG.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(gl)
    - pkgconfig32(glib-2.0)
    - pkgconfig(gtk-doc)
    - pkgconfig32(pixman-1)
    - pkgconfig32(xcb-render)
    - pkgconfig32(xext)
    - pkgconfig32(xrender)
    - pkgconfig32(xshmfence)
    - pkgconfig32(x11)
    - pkgconfig32(zlib)
replaces   :
    - cairo
    - devel : cairo-devel
    - docs : cairo-docs
patterns   :
    - devel : /usr/bin
setup      : |
    %apply_patches
    %meson_configure -Dsymbol-lookup=disabled \
        -Dfontconfig=enabled \
        -Dfreetype=enabled \
        -Dgtk_doc=true \
        -Dpng=enabled \
        -Dtee=enabled \
        -Dxcb=enabled \
        -Dxlib=enabled \
        -Dxlib-xcb=enabled \
        -Dzlib=enabled \
build      : |
    %ninja_build
install    : |
    %ninja_install
