name       : libxpm
version    : 3.5.15
release    : 12
source     :
    - https://www.x.org/releases/individual/lib/libXpm-3.5.15.tar.gz : 2a9bd419e31270593e59e744136ee2375ae817322447928d2abb6225560776f9
license    : MIT
summary    : X Pixmap (XPM) image file format library
component  : xorg.library
builddeps  :
    - pkgconfig32(glib-2.0)  #check
    - pkgconfig32(x11)
emul32     : yes
optimize   : speed
description: |
    libXpm provides support and common operations for the XPM pixmap format, which is commonly used in legacy X applications. XPM is an extension of the monochrome XBM bitmap specified in the X protocol.
setup      : |
    %patch -p1 < $pkgfiles/disable-not-applicable-tests.patch
    %configure --disable-open-zfile \
               --disable-static \
               --enable-unit-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
