name       : busybox
version    : 1.30.1
release    : 8
source     :
    - https://busybox.net/downloads/busybox-1.30.1.tar.bz2 : 3d1d04a4dbd34048f4794815a5c48ebb9eb53c5277e09ffffc060323b95dfbdc
license    : GPL-2.0-or-later
component  : system.boot
summary    : Statically linked binary providing simplified versions of system commands
description: |
    busybox is a single binary which includes versions of a large number of system commands, including a shell.
setup      : |
    cp $pkgfiles/config ./.config
build      : |
    %make
    %make busybox.links
install    : |
    install -Dm00755 busybox $installdir/bin/busybox
    install -Dm00644 busybox.links $installdir/bin/busybox.links
