name       : man-pages
version    : '6.03'
release    : 17
source     :
    - https://mirrors.edge.kernel.org/pub/linux/docs/man-pages/man-pages-6.03.tar.xz : 5f7f289d30b296b78116a08e7703df9375aa846b332b57dca47ddcbb7809fbbd
license    :
    - BSD-3-Clause
    - GPL-1.0-or-later
    - GPL-2.0-or-later
    - MIT
component  : system.utils
summary    : Linux manual pages
description: |
    A large collection of manual pages from the Linux Documentation Project (LDP).
mancompress: yes
rundeps    :
    - man-db
install    : |
    %make_install prefix=/usr

    # Remove conflicting files
    while read -r conflict; do
        rm -v $installdir/usr/share/man/$conflict
    done < $pkgfiles/man_conflicts
