name       : ruby-ffi
version    : 1.15.5
release    : 9
source     :
    - https://rubygems.org/downloads/ffi-1.15.5.gem : 6f2ed2fa68047962d6072b964420cba91d82ce6fa8ee251950c17fca6af3c2a0
homepage   : https://rubygems.org/gems/ffi
license    : BSD-3-Clause
component  : programming.ruby
summary    : Ruby FFI library
description: |
    An FFI implementation for Ruby.
builddeps  :
    - pkgconfig(ruby-3.1)
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc}
