name       : libaio
version    : 0.3.11
release    : 3
source     :
    - http://http.debian.net/debian/pool/main/liba/libaio/libaio_0.3.110.orig.tar.gz : e019028e631725729376250e32b473012f7cb68e1f7275bfc1bbcdd0f8745f7e
license    : LGPL-2.0-or-later
component  : kernel
summary    : Linux kernel AIO access library
description: |
    Linux kernel AIO access library
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        export CFLAGS="${CFLAGS} -fno-stack-protector"
    fi
    %make
install    : |
    %make_install prefix=$installdir/usr libdir=$installdir/%libdir%
    rm $installdir/%libdir%/*.a
